# .github/workflows/scheduled-builds.yml
name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs at 5 AM (see https://crontab.guru)
    - cron: '0 4 * * *'
jobs:
  job1:
    name: Checkout repo and choose gene
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: select new gene
        # Randomly select a gene and post it in github
        run: cd $GITHUB_WORKSPACE/util && sh select_new_gene.sh
      - name: Config user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: add, commit and push
        run: git commit -am "New gene of the day!" && git push origin main